name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt-get install -y clang gcc g++ build-essential nodejs python

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build compiler_lambda.go && go build judge_lambda.go

    - name: Test
      run: go test -v ./compiler/... ./judge/...
